version: '3.8'

services:
  dnd_database:
    container_name: dnd_database
    image: library/mysql:latest
    restart: always
    ports:
      - target: 3306
        published: 3307
        protocol: tcp
    env_file:
      - .env
  server:
    container_name: dnd_server
    restart: always
    build:
      context: .
      dockerfile: ./_docker/server/Dockerfile
    depends_on:
      - dnd_database
    volumes:
      - ./server/app:${SERVER_WORKDIR}/app
      - ./server/config:${SERVER_WORKDIR}/config
      - ./server/routes:${SERVER_WORKDIR}/routes
      - ./server/database:${SERVER_WORKDIR}/database
      - ./server/test:${SERVER_WORKDIR}/test
  nginx:
    container_name: dnd_nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./_docker/server/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - target: 80
        published: 81
        protocol: tcp
    depends_on:
      - server
  client:
    container_name: dnd_client
    restart: always
    build:
      context: .
      dockerfile: ./_docker/client/Dockerfile
      target: ${CLIENT_STAGE}
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    depends_on:
      - nginx
    volumes:
      - ./client/src/components:${CLIENT_WORKDIR}/src/components
      - ./client/src/router:${CLIENT_WORKDIR}/src/router
      - ./client/src/stores:${CLIENT_WORKDIR}/src/stores
      - ./client/src/views:${CLIENT_WORKDIR}/src/views
  ws:
    container_name: dnd_ws
    restart: always
    build:
      context: .
      dockerfile: ./_docker/ws/Dockerfile
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
    volumes:
      - ./ws:/var/www/ws
  ngrok:
    container_name: dnd_ngrok
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - 'start'
      - '--all'
      - '--config'
      - '/etc/ngrok.yml'
    volumes:
      - ./_docker/ngrok/ngrok.yaml:/etc/ngrok.yml
      - ./_docker/ngrok/ngrok.log:/var/log/ngrok.log
    ports:
      - target: 4040
        published: 4040
        protocol: tcp
    depends_on:
      - client
      - nginx
      - ws

networks:
  server-tier:
    driver: bridge
